#ifndef SMARTTOOLS_SMART_RESOUCES_STATUS_HPP
#define SMARTTOOLS_SMART_RESOUCES_STATUS_HPP

namespace smart::resouces::status
{

enum class StatusType
{
    NONE = 0,
    SENSOR_CHECK_READY,
    SENSOR_CHECK_DONE,
    SENSOR_ACTIVATION_READY,
    SENSOR_ACTIVATION_DONE,
    SENSOR_LOG_READER_READY,
    SENSOR_LOG_READER_DONE,

    REMOTE_ACTIVATION0_UNLOCK_READY,
    REMOTE_ACTIVATION0_UNLOCK_DONE,
    REMOTE_ACTIVATION1_UNLOCK_READY,
    REMOTE_ACTIVATION1_UNLOCK_DONE,
    REMOTE_CLEAR_SOURCES_READY,
    REMOTE_CLEAR_SOURCES_DONE,

    CUSTOMER_CHECK_UNLOCK_READY,
    CUSTOMER_CHECK_UNLOCK_DONE,

    RESOUCE_DELETE_CUSTOMER_READY,
    RESOUCE_DELETE_CUSTOMER_DONE,
    RESOUCE_DELETE_SUB_CUSTOMER_READY,
    RESOUCE_DELETE_SUB_CUSTOMER_DONE,
};

}

#endif //SMARTTOOLS_SMART_RESOUCES_STATUS_HPP
