#ifndef SMARTTOOLS_SMART_RESOUCES_STATUS_HPP
#define SMARTTOOLS_SMART_RESOUCES_STATUS_HPP

namespace smart::resouces::status
{

enum class StatusType
{
    NONE = 0,
    SENSOR_CHECK_READY,
    SENSOR_CHECK_DONE,
    SENSOR_ACTIVATION_READY,
    SENSOR_ACTIVATION_DONE,
    REMOTE_ACTIVATION0_UNLOCK_READY,
    REMOTE_ACTIVATION0_UNLOCK_DONE,
    REMOTE_ACTIVATION1_UNLOCK_READY,
    REMOTE_ACTIVATION1_UNLOCK_DONE,
};

}

#endif //SMARTTOOLS_SMART_RESOUCES_STATUS_HPP
